name: update

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash -CeEuo pipefail {0}

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macos-arm64
            os: macos-15
          - name: windows
            os: windows-latest
          - name: ubuntu
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}
    name: bench-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ahaoboy/js-engine-setup@v4

      - name: run
        run: |
          rm -rf ${{ matrix.name }}.json
          bun run --silent update > ${{ matrix.name }}.json
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ./${{ matrix.name }}.json
  update:
    needs: ["bench"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/download-artifact@v4
        with:
          path: windows
          pattern: windows
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          path: ubuntu
          pattern: ubuntu
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          path: macos-arm64
          pattern: macos-arm64
          merge-multiple: true

      - name: update json
        if: github.ref == 'refs/heads/main'
        run: |
          mv ./ubuntu/ubuntu.json ./ubuntu.json
          mv ./windows/windows.json ./windows.json
          mv ./macos-arm64/macos-arm64.json ./macos-arm64.json
          rm -rf ./ubuntu
          rm -rf ./windows
          rm -rf ./macos-arm64
          bun run --silent update:doc

      - name: commit
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "504595380@qq.com"
          git config --global user.name "ahaoboy-ci"
          git add .
          git commit -m"update"
          cat README.md

      - name: Upload README
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: README
          path: README.md

      - name: Push changes
        uses: ad-m/github-push-action@master
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Deploy to doc branch
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
          publish_branch: doc
          force_orphan: true
          cname: github.com
